server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # 查看路由匹配和过滤器执行情况
    reactor.netty: DEBUG                      # 查看底层网络转发情况
spring:
  config:
    import:
      - optional:classpath:application-secret.yml
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.101:8848
        namespace: public
        group: DEFAULT_GROUP
        service: gateway
      config:
        server-addr: 192.168.150.101:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/user/item/**,/user/category/**,/user/review/**,/home/**
          order: 10

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/user/order/**
          order: 10

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/user/wallet/**
          order: 10

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/user/chat/**,/user/chat-message/**,/user/chat-conversation/**
          order: 10

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          order: 10

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**,/admin-logs/**
          order: 20

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          order: 100

u:
  gateway:
    auth-secret: ${GATEWAY_AUTH_SECRET}
  swagger:
    title: u-trade接口文档
    description: u-trade接口文档
    email: d726760649@gmail.com
    concat: zhao
    package: com.u.admin.controller