spring:
  application:
    name: admin-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${admin.datasource.host}:${admin.datasource.port}/admin-service?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${admin.datasource.username}
    password: ${admin.datasource.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

admin:
  datasource:
    host: localhost
    port: 3306
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

sec:
  gateway:
    auth-secret: ${GATEWAY_AUTH_SECRET}
  jwt:
    admin-secret-key: ${JWT_ADMIN_SECRET}
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: ${JWT_USER_SECRET}
    user-ttl: 7200000
    user-token-name: token
