u:
  gateway:
    auth-secret: u-trade-gateway-jwt-secret-demo
  db:
    username: root
    password: 123
  rabbit:
    username: zhao
    password: 123
  jwt:
    admin-secret-key: u-trade-admin-jwt-secret-demo
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: u-trade-user-jwt-secret-demo
    user-ttl: 7200000
    user-token-name: token
  swagger:
    title: u-trade接口文档
    description: u-trade接口文档
    email: d726760649@gmail.com
    concat: zhao
    package: com.u.order.controller