spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.101:3306/order_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${u.db.username}
    password: ${u.db.password}
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 10000
    nacos:
      discovery:
        server-addr: 192.168.150.101:8848
        service: order-service
      config:
        server-addr: 192.168.150.101:8848
        file-extension: yml
        group: DEFAULT_GROUP
        refresh-enabled: true
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: ${u.rabbit.username}
    password: ${u.rabbit.password}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
  config:
    import:
      - optional:nacos:shared-application.yml?group=DEFAULT_GROUP
      # - optional:nacos:${spring.application.name}.yml?group=DEFAULT_GROUP
      - classpath:application-secret.yml
  data:
    redis:
      host: 192.168.150.101
      port: 6379
      password: ${u.redis.password}
server:
  port: 8084
