spring:
  data:
    redis:
      host: 192.168.150.101
      port: 6379
  elasticsearch:
    uris: http://192.168.150.101:9200
  application:
    name: sec-server
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${sec.datasource.host}:${sec.datasource.port}/sec-trade?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sec.datasource.username}
    password: ${sec.datasource.password}

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j

  rabbitmq:
    connection-timeout: 3000
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms
        multiplier: 2
        max-attempts: 3
        max-interval: 10000ms
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: false
    publisher-confirm-type: correlated
    publisher-returns: true
    host: 192.168.150.101
    port: 5672
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    virtual-host: /sec

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

sec:
  datasource:
    host: localhost
    port: 3306
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jwt:
    admin-secret-key: ${JWT_ADMIN_SECRET}
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: ${JWT_USER_SECRET}
    user-ttl: 7200000
    user-token-name: token

