sec:
  datasource:
    host: localhost
    port: 3306
    username: root
    password: cms321321

  jwt:
    admin-secret-key: sec_trade_admin_secret_key_fixed_123456
    user-secret-key: sec_trade_user_secret_key_fixed_654321
spring:
  rabbitmq:
    username: tjxt
    password: 123321