spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.101:3306/item_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${u.db.username}
    password: ${u.db.password}
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.101:8848
        service: item-service
      config:
        server-addr: 192.168.150.101:8848
        file-extension: yml
        group: DEFAULT_GROUP
        refresh-enabled: true
  config:
    import:
      - optional:nacos:shared-application.yml?group=DEFAULT_GROUP
      # - optional:nacos:${spring.application.name}.yml?group=DEFAULT_GROUP
      - classpath:application-secret.yml
  elasticsearch:
    uris: http://192.168.150.101:9200

  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: ${u.rabbit.username}
    password: ${u.rabbit.password}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
server:
  port: 8085
data:
  redis:
    host: 192.168.150.101
    port: 6379
